minutos/apps/core/urls.py
from django.urls import path
from . import views
from minutos.apps.userprofile import views as user_views

app_name = 'core'
urlpatterns = [
    path('', views.frontpage, name = 'frontpage'),
    path('privacypolicy/', views.privacy_policy, name = 'privacy'),
    path('termsofservice/', views.terms_of_service, name = 'terms'),
    path('plans/', views.plans, name = 'plans'),


    path('signup/', user_views.signup, name = 'signup'),
     path('logout/',user_views.logout, name = 'logout'),
    path('login/', user_views.login, name = 'login')
]

minutos/apps/team/urls.py
from django.urls import path
from . import views

app_name = 'team'

urlpatterns = [
    path('add/', views.add, name = 'add' )
]

minutos/apps/userprofile/urls.py
from django.urls import path
from . import views


app_name = 'userprofile'

urlpatterns = [
    
    path('editprofile/', views.edit_profile, name='edit_profile'),
    path('', views.my_account, name = 'myaccount'),
   
    #path('login/', auth_views.LoginView.as_view(template_name = 'login.html'), name = 'login'),

    #this logout view bellow it is a crap
    #path('logout/',auth_views.LogoutView.as_view(), name='logout'),
]

minutos/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('minutos.apps.core.urls')),
    path('myaccount/', include('minutos.apps.userprofile.urls')),
    path('team/',include('minutos.apps.team.urls')),
    path('admin/', admin.site.urls),
]

minutos/apps/core/models.py
from django.db import models

# Create your models here.

minutos/apps/team/models.py
from django.db import models
from django.contrib.auth.models import User

class Team(models.Model):
    ACTIVE = 'active'
    DELETED = 'deleted'
    CHOICE_STATUS = (
        (ACTIVE, 'Active'),
        (DELETED, 'Deleted')
    )

    title = models.CharField(max_length=255)
    members = models.ManyToManyField(User, related_name='teams')
    created_by = models.ForeignKey(User, related_name='created_teams', on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=CHOICE_STATUS, default=ACTIVE)

    class Meta:
        ordering = ['title']
    
    def __str__(self):
        return self.title

minutos/apps/userprofile/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='userprofile', related_query_name="userprofile", on_delete=models.CASCADE)
    active_team_id = models.IntegerField(default=0)

    def __str__(self):
        return str(self.user)

minutos/apps/core/views.py
from django.shortcuts import render

def frontpage(request):
    return render(request, 'frontpage.html')

def privacy_policy(request):
    return render(request, 'privacy.html')

def terms_of_service(request):
    return render(request, 'termsofservice.html')

def plans(request):
    return render(request, 'plans.html')

minutos/apps/team/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Team

@login_required
def add(request):
    if request.method == 'POST':
       title = request.POST.get('title')
       if title:
           team = Team.objects.create(title = title, created_by=request.user)
           team.members.add(request.user)
           team.save()

           userprofile = request.user
           userprofile.active_team_id = team.id
           userprofile.save()

           return redirect('userprofile:myaccount')
    return render(request, 'team_add.html') 

minutos/apps/userprofile/views.py
from django.contrib import auth, messages
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

from minutos.apps.team.models import Team

from .models import UserProfile



def signup(request):
    form = UserCreationForm()
    if request.method =='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.email = user.username
            user.save()

            userprofile = UserProfile.objects.create(user = user)
            login(request, user)
            return redirect('core:frontpage')
    return render(request, 'signup.html', {'form':form})

@login_required
def my_account(request):
    # teams = request.user.teams.all()
    print(request.user.userprofile)
    teams = request.user.teams.exclude(pk=request.user.id)
    
    return render(request, 'myaccount.html',{'teams':teams})

@login_required
def edit_profile(request):
    if request.method == 'POST':
        request.user.first_name = request.POST.get('first_name', '')
        request.user.last_name = request.POST.get('last_name', '')
        request.user.email = request.POST.get('email', '')
        request.user.save()
        
        messages.info(request,'The changes was saved' )
        return redirect('userprofile:myaccount')
    return render(request, 'edit_profile.html')

def login(request):
    if request.user.is_authenticated:
        return redirect('userprofile:myaccount')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(request, username=username, password=password)

        if not user:
            messages.error(request, 'Username or password incorrect')
            return render(request, 'login.html')
        else:
            auth.login(request, user)
            return redirect('userprofile:myaccount')
    return render(request, 'login.html')

def logout(request):
    auth.logout(request)
    return redirect('core:frontpage')

minutos/apps/core/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock title %} Minutos</title>
        <script src="https://unpkg.com/vue@next"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
        
    </head>
    <body>
        <!-- Navbar -->
        <div id="navbar-app">
            <nav class="navbar">

                <div class="navbar-brand">
                    <a href="{% url 'core:frontpage' %}" class="navbar-item" > <strong>Minutos</strong> </a>
                </div>

                <div class="navbar-menu">
                    <div class="navbar-end">
                        {% if not request.user.is_authenticated %}
                        <a href="{% url 'core:plans' %}" class="navbar-item">Plans</a>
                        {% endif %}
                    </div>
                    <div class="navbar-item">
                        <div class="buttons">
                            
                            {% if request.user.is_authenticated %}
                                <a href="{%url 'userprofile:myaccount'%}" class="button is-success">{%firstof request.user.get_full_name request.user.username%}</a>
                            {% else %}
                                <a href="{% url 'core:signup' %}" class="button is-success"> <strong>Sign Up</strong> </a>
                                <a href="{% url 'core:login' %}" class="button"> Log in </a>
                            {% endif %}
                                
                            
                        </div>
                    </div>
                </div>
            </nav>   
        </div>
        <!-- End Navbar -->

        <!-- Main -->

        <section class="section">
            
            {% if messages %}
                
                {% for message in messages %}
                    <div class="notification is-info">{{message}}</div>
                {% endfor %}
                    
            {% endif %}
                
            {% block main %}
                
            {% endblock main %}
                
        </section>
        <!-- End Main -->

        <!-- Footer -->
        <footer class="footer">
            <div class="columns is-multiline">
                <div class="column is-4">
                    <h2 class="subtitle">Minutos</h2>
                </div>
                <div class="column is-offset-6 is-2">
                    <ul>
                        <li><a href="">Contact</a></li>
                        <li><a href="{% url 'core:privacy' %}">Privacy Policy</a></li>
                        <li><a href="{% url 'core:terms' %}">Terms of Service</a></li>
                    </ul>
                </div>
                <div class="column is-12 has-text-centered">
                    <p>Copyright (C) {%now 'Y'%}</p>
                </div>
            </div>
        </footer>
        <!-- End Footer -->

        
        {% block js %}
            
        {% endblock js %}
            
    </body>
</html>

minutos/apps/core/templates/frontpage.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Home |{% endblock title %}


{% block main %}
    <section class="hero is-medium is-light is-bold">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">Welcome to Minutos</h1>
                <h2 class="subtitle">Time Tracking made simple</h2>
            </div>
        </div>
    </section>

    <div class="container">
        <div class="columns">
            <div class="column is-8 is-offset-2">
                <div class="columns is-align-items mt-6">
                    <div class="column is-4 image">
                        <img src="{% static 'images/features-tracktime.jpg' %}" alt="">
                    </div>
                    <div class="column is-8 text">
                        <h2 class="subtitle">Simple time tracking</h2>
                        <p>Time tracking made simple. Time tracking made simple.Time tracking made simple.Time tracking made simple.Time tracking made simple.</p>
                    </div>
                </div>

                <div class="columns is-align-items mt-6">
                    <div class="column is-8 text">
                        <h2 class="subtitle">Simple time tracking</h2>
                        <p>Time tracking made simple. Time tracking made simple.Time tracking made simple.Time tracking made simple.Time tracking made simple.</p>
                    </div>
                    <div class="column is-4 image">
                        <img src="{% static 'images/features-tracktime.jpg' %}" alt="">
                    </div>
                </div>

                <div class="columns is-align-items mt-6">
                    <div class="column is-4 image">
                        <img src="{% static 'images/features-tracktime.jpg' %}" alt="">
                    </div>
                    <div class="column is-8 text">
                        <h2 class="subtitle">Simple time tracking</h2>
                        <p>Time tracking made simple. Time tracking made simple.Time tracking made simple.Time tracking made simple.Time tracking made simple.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns is-align-items-center mt-6">
            <div class="column is-4 is-offset-4 has-text-centered">
                <h2 class="subtitle">Let's get started</h2>
                <a href="" class="button is-success is-large">Get a Free Account</a>
            </div>
        </div>
    </div>
{% endblock main %}
<!-- parou no 19:03 -->
    
    

minutos/apps/core/templates/plans.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Plans |{% endblock title %}


{% block main %}
<section class="hero is-medium is-light is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">Plans</h1>
            <h2 class="subtitle">Find the most suitable plan for your team</h2>
        </div>
    </div>
</section>
<div class="columns mt-6">
    <div class="column is-3">
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">Free</p>
                        <p class="subtitle is-6">$0</p>
                    </div>
                </div>
                <div class="content">
                    <ul>
                        <li>3 projects</li>
                        <li>1 member</li>
                        <li>10 tasks per project</li>
                    </ul>
                    <hr>
                    <a href="" class="button is-primary">Get Started</a>
                </div>
            </div>
        </div>
    </div>

    <div class="column is-3">
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">Basic</p>
                        <p class="subtitle is-6">$5</p>
                    </div>
                </div>
                <div class="content">
                    <ul>
                        <li>10 projects</li>
                        <li>15 members</li>
                        <li>30 tasks per project</li>
                    </ul>
                    <hr>
                    <a href="" class="button is-primary">Get Started</a>
                </div>
            </div>
        </div>
    </div>

    <div class="column is-3">
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">Pro</p>
                        <p class="subtitle is-6">$10</p>
                    </div>
                </div>
                <div class="content">
                    <ul>
                        <li>25 projects</li>
                        <li>50 members</li>
                        <li>100 tasks per project</li>
                    </ul>
                    <hr>
                    <a href="" class="button is-primary">Get Started</a>
                </div>
            </div>
        </div>
    </div>

    <div class="column is-3">
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">Premium</p>
                        <p class="subtitle is-6">$20</p>
                    </div>
                </div>
                <div class="content">
                    <ul>
                        <li>50 projects</li>
                        <li>100 members</li>
                        <li>200 tasks per project</li>
                    </ul>
                    <hr>
                    <a href="" class="button is-primary">Get Started</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

minutos/apps/core/templates/privacy.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Privacy Policy |{% endblock title %}


{% block main %}
<section class="hero is-medium is-light is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">Privacy Policy</h1>
            <h2 class="subtitle">Some random information</h2>
        </div>
    </div>
</section>
{% endblock main %}
    

minutos/apps/core/templates/termsofservice.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Terms of Service |{% endblock title %}


{% block main %}
<section class="hero is-medium is-light is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">Terms of Service</h1>
            <h2 class="subtitle">Some random information</h2>
        </div>
    </div>
</section>
{% endblock main %}

minutos/apps/team/templates/team_add.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Edit Profile |{% endblock title %}


{% block main %}

<nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
        <li><a href="">Dashboard</a></li>
        <li class=""><a href="{% url 'userprofile:myaccount' %}" >My Account</a></li>
        <li class="is-active"><a href="{% url 'team:add' %}" aria-label="page">Add Team</a></li>
    </ul>
</nav>

<div class="columns" id="team-app">
    <div class="column is-4">
        <h1 class="title">Add team</h1>
        <form action="" method="POST" @submit="validateForm">
            {% csrf_token %}
            <div class="field">
                <label for="">Title</label>
                <div class="control">
                    <input type="text" id="id_title" name="title" v-model="title">
                </div>
            </div>
            <div class="notification is-danger" v-if="errors.length">
                <p v-for="error in errors">[[error]]</p>
            </div>
            <div class="field">
                <div class="control">
                    <button class="button is-success">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>


{% endblock main %}


{% block js %}
    <script>
        const TeamApp = {
            data(){
                return{
                    title: '',
                    errors: [],
                }
            },
            delimiters: ['[[',']]'],
            methods:{
                validateForm(e){
                    this.errors = []
                    if(this.title){
                        return true
                    }
                    e.preventDefault()
                    this.errors.push('The title field is missing')
                }
            }
        }
        Vue.createApp(TeamApp).mount('#team-app')
    </script>
{% endblock js %}
    

minutos/apps/userprofile/templates/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Edit Profile |{% endblock title %}


{% block main %}

<nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
        <li><a href="">Dashboard</a></li>
        <li class=""><a href="{% url 'userprofile:myaccount' %}" >My Account</a></li>
        <li class="is-active"><a href="{% url 'userprofile:edit_profile' %}" aria-label="page">Edit Profile</a></li>
    </ul>
</nav>

<!-- <section class="hero is-medium is-light is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">Edit Profile</h1>
            <h2 class="subtitle">Find the most suitable plan for your team</h2>
        </div>
    </div> -->
</section>

<div class="columns">
    <div class="column is-4">
        <h1 class="title">Edit Profile</h1>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="field">
                <label for="">First Name</label>
            
                <div class="control">
                    <input type="text" name="first_name" id="first_name" class="input" 
                    {% if request.user.first_name %}value="{{request.user.first_name}}"{% endif %}>
                </div>
            </div>

            <div class="field">
                <label for="">Last Name</label>
            
                <div class="control">
                    <input type="text" name="last_name" id="last_name" class="input" 
                    {% if request.user.last_name %}value="{{request.user.last_name}}"{% endif %}>
                </div>
            </div>

            <div class="field">
                <label for="">Email</label>
            
                <div class="control">
                    <input type="email" name="email" id="email" class="input" {% if request.user.email %}value="{{request.user.email}}"{% endif %}>
                </div>
            </div>

            <div class="field">
                
            </div>
            <div class="control">
                <button class="button is-success">Save Changes</button>
            </div>
        </form>
    </div>
</div>
{%endblock main%}

minutos/apps/userprofile/templates/login.html
{% extends 'base.html' %}

{% block title %} Log in | {% endblock title %}


{% block main %}
<section class="hero is-medium is-light is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">Log in</h1>
            <h2 class="subtitle">Log in to your account and start tracking time</h2>
        </div>
    </div>
</section>

<div class="columns" id="signup-app">
    <div class="column is-6 is-offset-3">
        <form action="" method="POST" class="mt-6" novalidate >
            {% csrf_token %}
            
            {% if form.errors %}
                <div class="notification is-danger">
                    {{form.non_fields_errors}}
                    
                    {% for field in form  %}
                        {% if field.errors %}{{field.label}}: {{field.errors|striptags}}{% endif %}
                            
                    {% endfor %}
                        
                </div>
            {% endif %}
            
            <div class="field">
                <label for="id_username">Email</label>
                <div class="control">
                    <input type="email" name="username" id="id_username" class="input">
                </div>
            </div>
            
            <div class="field">
                <label for="id_password1">Password</label>
                <div class="control">
                    <input type="password" name="password" id="id_password" class="input">
                </div>
            </div> 
            
            
            <div class="field">
                <div class="control">
                    <button class="button is-success">Log in</button>
                </div>
            </div>
        </form>
        <hr>
        <h2 class="subtitle">Don't have an account?</h2>
        <a href="{%url 'core:signup'%}">Create an account for free</a>
    </div>
</div>
{% endblock main %}

minutos/apps/userprofile/templates/myaccount.html
{% extends 'base.html' %}


{% block title %}My Account |{% endblock title %}


{% block main %}
    
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="">Dashboard</a></li>
            <li class="is-active"><a href="{% url 'userprofile:myaccount' %}" aria-label="page">My Account</a></li>
        </ul>
    </nav>
    <div class="columns">
        <div class="column is-6">
            <div class="media mb-4">
                <div class="media-left">
                    
                </div>
                <div class="media-content">
                    <p class="title is-3">{%firstof user.get_full_name user.username%}</p>
                    <p class="subtitle is-6">{{user.email}}</p>
                </div>
            </div>
            <a href="{% url 'userprofile:edit_profile' %}" class="button is-info">Edit Profile</a>
             <a href="{% url 'core:logout' %}" class="button is-danger">Log out</a>
        </div>
    </div>
    <hr>
    <div class="columns">
        <div class="column is-12">
            <h2 class="subtitle">Teams</h2>
            <a href="{%url 'team:add'%}" class="button is-success">Add Team</a>
        </div>
    </div>
    
    <div class="columns">
        <div class="row">
            
        </div>
        {% for team in teams %}
        <div class="column is-4">
            <div class="notification">
                <h3 class="is-size-5">{{team.title}} 
                {% if team.created_by == request.user %} (Ownner){% endif %}
                </h3>
                <h3 class="is-size-6">SHOW PLAN HERE</h3>
                <hr>
                <a href="" class="button is-success">Details</a>
                <a href="" class="button is-info">Activate</a>
            </div>
        </div>
            
        {% endfor %}
            
    </div>
{% endblock main %}
    

minutos/apps/userprofile/templates/signup.html
{% extends 'base.html' %}

{% block title %} Sign up | {% endblock title %}


{% block main %}
<section class="hero is-medium is-light is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">Sign Up</h1>
            <h2 class="subtitle">Get free account and start tracking time</h2>
        </div>
    </div>
</section>

<div class="columns" id="signup-app">
    <div class="column is-6 is-offset-3">
        <form action="" method="POST" class="mt-6" v:on:submit="validateForm">
            {% csrf_token %}
            
            {% if form.errors %}
                <div class="notification is-danger">
                    {{form.non_fields_errors}}
                    
                    {% for field in form  %}
                        {% if field.errors %}{{field.label}}: {{field.errors|striptags}}{% endif %}
                            
                    {% endfor %}
                        
                </div>
            {% endif %}
            <div class="notification is-danger" v-if="errors.length">
                <p v-for="error in errors">
                    [[ error ]]
                </p>
            </div>
            <div class="field">
                <label for="id_username">Email</label>
                <div class="control">
                    <input type="email" name="username" id="id_username" class="input" v-model="username">
                </div>
            </div>
            
            <div class="field">
                <label for="id_password1">Password</label>
                <div class="control">
                    <input type="password" name="password1" id="id_password1" class="input" v-model="password1">
                </div>
            </div> 
            
            <div class="field">
                <label for="id_password2">Password</label>
                <div class="control">
                    <input type="password" name="password2" id="id_password2" class="input" v-model="password2">
                </div>
            </div>
            <ul class="password-helt-text">
                <li v-if="password1.length < 8">Your password must contain at least 8 characters</li>
                <li v-if="!isNaN(password1)">Your password can't be entirely numeric </li>
            </ul>
            <div class="field">
                <div class="control">
                    <button class="button is-success">Sign Up</button>
                </div>
            </div>
        </form>
        <hr>
        
        <h2 class="subtitle">Already have an account?</h2>
        <a href="{%url 'core:login'%}">Log in</a>
    </div>
</div>
{% endblock main %}


{% block js %}
    <script>
        
        const SignupApp = {
            data(){
                return{
                    username: '',
                    password1: '',
                    password2: '',
                    errors: []
                }
                
            },
            delimiters:['[[',']]'],
            methods:{
                validateForm(event){
                    this.errors = []

                    if (!this.validateEmail(this.username)){
                        this.errors.push('Your e-mail address in not valid')
                    }
                    
                    if (this.password1 == ''){
                        this.errors.push('Your password is missing')
                    }

                    if (this.password1.length < 8){
                        this.errors.push('Your password must be at least 8 characters')
                    }

                    if (!isNaN(this.password1)){
                        this.errors.push("Your password can't be entirely numeric")
                    }

                    if (this.password1 !== this.password2){
                        this.errors.push("Your passwords does not match")
                    }
                    if (this.errors.length){
                        event.preventDefault()
                        return false
                    }
                    else{
                        return true
                    }
                },
                validateEmail(email) {
                    if (/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/.test(email)) {
                        return true
                    }
                        return false
                    }
            }
        }
        Vue.createApp(SignupApp).mount('#signup-app')
    </script>
{% endblock js %}
    
    
    